### ISSUE TITLE
version 5.30.0 - sort code range 304065 - 304067, always failing to  checkNotImplementedError

### ISSUE THREAD

**Issue by sk1234** [mpetruska/uk-modulo-scala#19]
MOD table (v530.txt) has only one entry for the new changes as below:

304065 304067 MOD11 0 0 3 2 9 8 5 7 6 5 4 3 2 1 9

This has an exception code of 9 (last digit), however, as per vocalink doc, there is no individual exception 9 (has to be 2 & 9) as below:

“Exception 2 and 9 Only occurs for some standard modulus 11 checks, when there is a 2 in the exception column for the first check for a sorting code and a 9 in the exception column for the second check for the same sorting code.”

This is always resulting to default checkNotImplementedError error for sort code range 304065 304067.

V5.40.0 has taken out the exception code 9, however, this is not confirmed in the docs if this is a fix to earlier version v5.30.0 (this just mentions that "Amended sort code range 304065-304067")

Can you please confirm if additions to v5.30.0 were not correct and has been fixed in v5.40.0?

**Comment by mpetruska** [comment]
Yes, I double checked, the changes that lead to the problem were made in the specification. I also discovered this, but version 5.40 of the spec came out just before I made an inquiry to VocaLink, in which the problem was fixed. At that point I was convinced that VocaLink discovered the problem in the specification and version 5.40 fixes that.

For reference:
- Version 5.30 of the specification can be found here: https://www.vocalink.com/media/3047/vocalink-validating-account-numbers-v530.pdf
- Version 5.40 of the specification can be found here: https://www.vocalink.com/media/3061/vocalink-validating-account-numbers-v540.pdf
